[passwords]
marshallr = "streamlit12"
chelseat = "streamlit12"
zulfaj = "streamlit12"
carav = "streamlit12"
sergiok = "streamlit12"
onesiphom = "streamlit12"

[google] 
type = "service_account"
project_id = "ccs-extract-tracking"
private_key_id = "348aa1a07ffd4b898b79fdd12ac8e527cbafe794"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCyOzM8fAvkVCgQ\nVhL1cXc7AUvRFjV9DscltgNSPB/e8ffo+ZK7XWlBGnHiki9pZwbk6ksXfbcdDnID\nnjaNWHJBJDPlUNyyhO35c8wxKmzrgW3+RESxBSZQXnH3w4DAFkia/IfXW6sc22Ho\ngdbtNUqufzgZK9b5ZPPTmU8Gf/UdnIlvW6V3NVe+r3C7qRlMmDc5xf7ysX8a5vTI\nk+uppeFCRoLs5cb5oIXfG9UCMung8Cas2yDdmIOA0117OhGjz0QX1p3zy/EcZlcU\ndpL50u+ogrXryaAYXOs4t+Y2GrKXDy3MtTn1N9Gn+Xmh8HJP9qfA4pLaNrRV/TPD\nANlzLF9jAgMBAAECggEAVm0NmdlfHN/QM6fBdsKIOhUVUjTuSA+38ynxL1nXbJEy\nEYegJvoTdY3gxqjzk61xcuTH+AKunkjocaexNVY7xSnMfnj5JBoAmdOUowy7F3JC\nR6eMFbj1DMjXg/kKAFtt5rXpGz2o2ovpTMlVUt5iMf6f0djn3DSfZa60WucGkc4M\nuc3fpy7GLKNErFSdo/XjRb9i4MY2HwGf7CCZriWxAliXZjCDTXVbeOWJbwivyy7n\ngPJcwNDZRopMQY5D6ORaY3T+dXlAgQufu0D/UnblHYIRKK1Tx63D+v6j4rEwPFBE\na0Ocd7QuGy9XxETnSG33U6c6pwlH+IrTKi+eIy67xQKBgQDb0YaVqla1xA8PLvw5\nGfmY2OOdDvRy/JpV09CgeLW5pdp320OCvO/nQ6QSgeyQ5VOc4pkIIGstvWGjekBT\neZ1FpNvuLO5eQa8xgWq2yfr2vKHgg6c5/8H7s2OaYrlChYFhzvc7AmnRWSvZ6wIL\nkKttbP2pwpU8ETzW3nnOEm5tVQKBgQDPkVE2quqRcA9lQRaQc52ASDBZwqM+C21j\nJFWgqYGD3c3DO0wyklKcwrK0CnZHfMKCqYJ1Ykk12jqJMVEFP9ekH8+kiBZWQzC2\n2CkmObGbe3lpYWVjhbd5min0EPsBKAM7cFoGchKNEyswYe2cixN4NpNh3cv4eS+1\nXLm6IrxZ1wKBgQCGxYbDekVhegxVndQMWm2aldevsryTR2aEmrI9wOSCJzqz454X\nqSlZXDJbGodlKwVBmfiDcATmbUdQyKJpy5VuXq5s7+VRqunz60n3Og0BfBOvqGg9\n+h3/6TN3M3IsY9g4lIEmD8u7C/YDzL9bQd6o33sCuwduZY8smgiKHOjRZQKBgEwK\nd48odECNpgY5HxQSVuvtBlGL3ZPYSd2dLQVrs7fkZQIV0idgtYUaSq9secJcsUF+\n6f0o4Zsp9HHYME9VASHuSXqEJHK7sLf7Xq/TSP6l8Gert6ILFZkl4iK4qcvVpcF7\num9MEQG/uP3DknHb/Wj3zWx3/cZsVw8BBkVrfkcHAoGAV9dGCPAs2PXrqkbvCpiy\nfJAUhOjZQIEQdh0QfT/RytSztCFvwarujtfM7/BHMi8vwZCab0ZJcSuH0Fe/WYuM\nCXwG51x7kqubMqt9k3HOpwpaZs7C1CiajjsqWZ8Z4+ilSL2vjxzVWURFIVLGLeik\nKozunYGUhw1hTtnnld7dEoY=\n-----END PRIVATE KEY-----\n"
client_email = "ccs-extracts@ccs-extract-tracking.iam.gserviceaccount.com"
client_id = "104372816146423497938"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ccs-extracts%40ccs-extract-tracking.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
